### ISSUE TITLE
Not showing translated text

### ISSUE THREAD

**Issue by smoochy** [sebcaps/hydrao#6]
So I finally received my API Key and could test your integration.

I have added your Integration into HACS.

I have set the language of my Home Assistant user to English.

When adding the integration via Settings -> Devices & Services -> Add Integration, I can see the Hydrao Integration. But when selecting it, no translated text is shown in the fields.

![image](https://github.com/sebcaps/hydrao/assets/34371932/615f6850-fadc-470e-a0da-ce0caaf33fe5)

The same happens, when the language of the user is set to English (GB) or German.

Only, if I set the language of the user to French, the text is showing up:

![image](https://github.com/sebcaps/hydrao/assets/34371932/6ed3944a-6864-4d42-93e6-13c65c05efb0)

So apparently my PR and editing the few files is not enough to 

It has nothing to do with Dark or Light mode.

**Comment by sebcaps** [comment]
My bad 😔.
I forget to generate a new release after merging your contribution.
It's done now and ok in version 0.0.4.
Enjoy.
![Screenshot_20240412-083339](https://github.com/sebcaps/hydrao/assets/24374878/15a753c1-bcb4-40d4-8eae-6b241d0f7fa3)

**Comment by smoochy** [comment]
No worries. Thanks for creating the build. Wasn't aware that HACS is only considering the releases.

I would like to experiment a bit more. Can you point me towards a guide, that I could take my fork, try to add or fix stuff (English translation is not showing up, names or sensors are in French etc) without having to bother you all the time. In addition I can't test those changes before creating a PR.

Cheers.

**Comment by sebcaps** [comment]
Hello, you can use devcontainer in the repo to try your dev before submitting a PR it will setup the environment and allow to test/debug.
Sorry no ressources in EN to use it, but I guess  you can easily find some.
